routes:
  - route: /signin
    rewrite:
      to: /signin.html
  - route: /signup
    rewrite:
      to: /signup.html
  - route: /{**route}
    rewrite:
      to: /index.html

rewrites:
  - source: /signin.html
    destination: /signin.html
  - source: /signup.html
    destination: /signup.html
  - source: /index.html
    destination: /index.html
  - source: /search
    destination: /search.html
  - source: /getstarted
    destination: /getstarted.html
  - source: /getstartedwelcome
    destination: /getstartedwelcome.html
  - source: /accountcreated
    destination: /accountcreated.html
  - source: /forgotpassword
    destination: /forgotpassword.html
  - source: /forgotpasswordemail
    destination: /forgotpasswordemail.html
  - source: /newpassword
    destination: /newpassword.html
  - source: /myprofile
    destination: /myprofile.html
  - source: /myaddress
    destination: /myaddress.html
  - source: /confirmnumber
    destination: /confirmnumber.html
  - source: /verifynumber
    destination: /verifynumber.html
  - source: /shop
    destination: /shop.html
  - source: /product
    destination: /product.html
  - source: /shop/filter
    destination: /shop/filter.html
  - source: /editprofile
    destination: /editprofile.html
  - source: /emptycart
    destination: /emptycart.html
  - source: /cart
    destination: /cart.html
  - source: /order
    destination: /order.html
  - source: /ordersuccessful
    destination: /ordersuccessful.html
  - source: /orderfail
    destination: /orderfail.html
  - source: /orderhistory
    destination: /orderhistory.html
  - source: /checkout/shipping
    destination: /checkout/shipping.html
  - source: /checkout/payment
    destination: /checkout/payment.html
  - source: /checkout
    destination: /checkout.html
  - source: /paymentmethod
    destination: /paymentmethod.html
  - source: /AddNewCard
    destination: /AddNewCard.html
  - source: /SpecificProduct
    destination: /SpecificProduct.html
  - source: /sendreview
    destination: /sendreview.html
  - source: /reviews
    destination: /reviews.html
  - source: /promocode
    destination: /promocode.html
  - source: /myaddress/new
    destination: /myaddress/new.html
  - source: /Wishlist
    destination: /Wishlist.html

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_ROCK_08A6BA503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
        env:
          CI: "false"
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request JobS
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_ROCK_08A6BA503 }}
          action: "close"
